#ifndef CALLBACKAPI_CNRT_ID_H_
#define CALLBACKAPI_CNRT_ID_H_

#ifdef __cplusplus
extern "C" {
#endif
typedef enum {
  CNPAPI_CNRT_TRACE_CBID_cnrtAddParam = 0,
  CNPAPI_CNRT_TRACE_CBID_cnrtAllocParam = 1,
  CNPAPI_CNRT_TRACE_CBID_cnrtClearCurrentThreadAffinity = 2,
  CNPAPI_CNRT_TRACE_CBID_cnrtConvertDoubleToHalf = 3,
  CNPAPI_CNRT_TRACE_CBID_cnrtConvertFloatToHalf = 4,
  CNPAPI_CNRT_TRACE_CBID_cnrtConvertHalfToDouble = 5,
  CNPAPI_CNRT_TRACE_CBID_cnrtConvertHalfToFloat = 6,
  CNPAPI_CNRT_TRACE_CBID_cnrtCopyFunction = 7,
  CNPAPI_CNRT_TRACE_CBID_cnrtCopyKernelParamsBuffer = 8,
  CNPAPI_CNRT_TRACE_CBID_cnrtCreateEvent = 9,
  CNPAPI_CNRT_TRACE_CBID_cnrtCreateFunction = 10,
  CNPAPI_CNRT_TRACE_CBID_cnrtCreateNotifier = 11,
  CNPAPI_CNRT_TRACE_CBID_cnrtCreateQueue = 12,
  CNPAPI_CNRT_TRACE_CBID_cnrtCreateRuntimeContext = 13,
  CNPAPI_CNRT_TRACE_CBID_cnrtCreateStream = 14,
  CNPAPI_CNRT_TRACE_CBID_cnrtDestoryParam = 15,
  CNPAPI_CNRT_TRACE_CBID_cnrtDestroyEvent = 16,
  CNPAPI_CNRT_TRACE_CBID_cnrtDestroyFunction = 17,
  CNPAPI_CNRT_TRACE_CBID_cnrtDestroyKernelParamsBuffer = 18,
  CNPAPI_CNRT_TRACE_CBID_cnrtDestroyNotifier = 19,
  CNPAPI_CNRT_TRACE_CBID_cnrtDestroyQueue = 20,
  CNPAPI_CNRT_TRACE_CBID_cnrtDestroyRuntimeContext = 21,
  CNPAPI_CNRT_TRACE_CBID_cnrtDestroyStream = 22,
  CNPAPI_CNRT_TRACE_CBID_cnrtEventElapsedTime = 23,
  CNPAPI_CNRT_TRACE_CBID_cnrtExtractFunction = 24,
  CNPAPI_CNRT_TRACE_CBID_cnrtFilterReshape = 25,
  CNPAPI_CNRT_TRACE_CBID_cnrtFree = 26,
  CNPAPI_CNRT_TRACE_CBID_cnrtFreeArray = 27,
  CNPAPI_CNRT_TRACE_CBID_cnrtFreeHost = 28,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetCurrentChannel = 29,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetCurrentDevice = 30,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetDataShape = 31,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetDeviceAffinity = 32,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetDeviceCount = 33,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetDeviceHandle = 34,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetFunctionMemUsed = 35,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetFunctionNumber = 36,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetHostDataCount = 37,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetHostWeightCount = 38,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetInputDataDesc = 39,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetKernelParamsBuffer = 40,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetModelMemUsed = 41,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetModelSize = 42,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetOutputDataDesc = 43,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetParam = 44,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetRuntimeContextInfo = 45,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetStackMem = 46,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetTaskPriority = 47,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetVersion = 48,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetWeightDesc = 49,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetWeightDescArray = 50,
  CNPAPI_CNRT_TRACE_CBID_cnrtInit = 51,
  CNPAPI_CNRT_TRACE_CBID_cnrtInitFunctionConstMemory = 52,
  CNPAPI_CNRT_TRACE_CBID_cnrtInitFunctionInstMemory = 53,
  CNPAPI_CNRT_TRACE_CBID_cnrtInitFunctionIntmdMemory = 54,
  CNPAPI_CNRT_TRACE_CBID_cnrtInitFunctionMemory = 55,
  CNPAPI_CNRT_TRACE_CBID_cnrtInitFunctionMemory_V2 = 56,
  CNPAPI_CNRT_TRACE_CBID_cnrtInitRuntimeContext = 57,
  CNPAPI_CNRT_TRACE_CBID_cnrtInvokeFunction = 58,
  CNPAPI_CNRT_TRACE_CBID_cnrtInvokeFunctionExtra = 59,
  CNPAPI_CNRT_TRACE_CBID_cnrtInvokeFunction_V2 = 60,
  CNPAPI_CNRT_TRACE_CBID_cnrtInvokeKernel = 61,
  CNPAPI_CNRT_TRACE_CBID_cnrtInvokeRuntimeContext = 62,
  CNPAPI_CNRT_TRACE_CBID_cnrtKernelParamsBufferAddParam = 63,
  CNPAPI_CNRT_TRACE_CBID_cnrtKernelParamsBufferMarkInput = 64,
  CNPAPI_CNRT_TRACE_CBID_cnrtKernelParamsBufferMarkOutput = 65,
  CNPAPI_CNRT_TRACE_CBID_cnrtKernelParamsBufferMarkStatic = 66,
  CNPAPI_CNRT_TRACE_CBID_cnrtLoadModel = 67,
  CNPAPI_CNRT_TRACE_CBID_cnrtLoadModelFromMem = 68,
  CNPAPI_CNRT_TRACE_CBID_cnrtMalloc = 69,
  CNPAPI_CNRT_TRACE_CBID_cnrtMallocBatch = 70,
  CNPAPI_CNRT_TRACE_CBID_cnrtMallocBatchByDesc = 71,
  CNPAPI_CNRT_TRACE_CBID_cnrtMallocBatchByDescArray = 72,
  CNPAPI_CNRT_TRACE_CBID_cnrtMallocBufferEx = 73,
  CNPAPI_CNRT_TRACE_CBID_cnrtMallocByDesc = 74,
  CNPAPI_CNRT_TRACE_CBID_cnrtMallocByDescArray = 75,
  CNPAPI_CNRT_TRACE_CBID_cnrtMallocFrameBuffer = 76,
  CNPAPI_CNRT_TRACE_CBID_cnrtMallocHost = 77,
  CNPAPI_CNRT_TRACE_CBID_cnrtMemcpy = 78,
  CNPAPI_CNRT_TRACE_CBID_cnrtMemcpyBatch = 79,
  CNPAPI_CNRT_TRACE_CBID_cnrtMemcpyBatchByDesc = 80,
  CNPAPI_CNRT_TRACE_CBID_cnrtMemcpyBatchByDescArray = 81,
  CNPAPI_CNRT_TRACE_CBID_cnrtMemcpyByDesc = 82,
  CNPAPI_CNRT_TRACE_CBID_cnrtMemcpyByDescArray = 83,
  CNPAPI_CNRT_TRACE_CBID_cnrtMemset = 84,
  CNPAPI_CNRT_TRACE_CBID_cnrtNotifierDuration = 85,
  CNPAPI_CNRT_TRACE_CBID_cnrtPlaceEvent = 86,
  CNPAPI_CNRT_TRACE_CBID_cnrtPlaceNotifier = 87,
  CNPAPI_CNRT_TRACE_CBID_cnrtQueryCoreVersion = 88,
  CNPAPI_CNRT_TRACE_CBID_cnrtQueryModelParallelism = 89,
  CNPAPI_CNRT_TRACE_CBID_cnrtQueryModelStackSize = 90,
  CNPAPI_CNRT_TRACE_CBID_cnrtReshapeNCHWToNHWC = 91,
  CNPAPI_CNRT_TRACE_CBID_cnrtReshapeNHWCToNCHW = 92,
  CNPAPI_CNRT_TRACE_CBID_cnrtRuntimeContextCreateQueue = 93,
  CNPAPI_CNRT_TRACE_CBID_cnrtRuntimeContextDestroyQueue = 94,
  CNPAPI_CNRT_TRACE_CBID_cnrtRuntimeContextFree = 95,
  CNPAPI_CNRT_TRACE_CBID_cnrtRuntimeContextFreeArray = 96,
  CNPAPI_CNRT_TRACE_CBID_cnrtRuntimeContextMallocByDesc = 97,
  CNPAPI_CNRT_TRACE_CBID_cnrtRuntimeContextMallocByDescArray = 98,
  CNPAPI_CNRT_TRACE_CBID_cnrtRuntimeContextMemcpyByDesc = 99,
  CNPAPI_CNRT_TRACE_CBID_cnrtRuntimeContextMemcpyByDescArray = 100,
  CNPAPI_CNRT_TRACE_CBID_cnrtRuntimeContextSyncQueue = 101,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetCurrentChannel = 102,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetCurrentDevice = 103,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetCurrentThreadAffinity = 104,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetHostDataLayout = 105,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetHostWeightLayout = 106,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetRuntimeContextChannel = 107,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetRuntimeContextDataParallelism = 108,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetRuntimeContextDeviceId = 109,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetRuntimeContextInstConstShareble = 110,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetStackMem = 111,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetTaskPriority = 112,
  CNPAPI_CNRT_TRACE_CBID_cnrtSyncQueue = 113,
  CNPAPI_CNRT_TRACE_CBID_cnrtSyncStream = 114,
  CNPAPI_CNRT_TRACE_CBID_cnrtTopologyGetCpuRelatedDevices = 115,
  CNPAPI_CNRT_TRACE_CBID_cnrtTopologyGetNearestDevices = 116,
  CNPAPI_CNRT_TRACE_CBID_cnrtTopologyGetRelationship = 117,
  CNPAPI_CNRT_TRACE_CBID_cnrtUnloadModel = 118,
  CNPAPI_CNRT_TRACE_CBID_cnrtUpdateWeightData = 119,
  CNPAPI_CNRT_TRACE_CBID_cnrtUpdateWeightDataArray = 120,
  CNPAPI_CNRT_TRACE_CBID_cnrtWaitEvent = 121,
  CNPAPI_CNRT_TRACE_CBID_cnrtDestroy = 122,
  CNPAPI_CNRT_TRACE_CBID_cnrtInvokeCnrtKernelExtra = 123,
  CNPAPI_CNRT_TRACE_CBID_cnrtInvokeRuntimeContext_V2 = 124,
  CNPAPI_CNRT_TRACE_CBID_cnrtCreateParamDesc,
  CNPAPI_CNRT_TRACE_CBID_cnrtCreateParamDescArray,
  CNPAPI_CNRT_TRACE_CBID_cnrtDestroyParamDesc,
  CNPAPI_CNRT_TRACE_CBID_cnrtDestroyParamDescArray,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetShapeToParamDesc,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetNameToParamDesc,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetDataTypeToParamDesc,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetShapeFromParamDesc,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetNameFromParamDesc,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetIdFromParamDesc,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetDataTypeFromParamDesc,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetDimOrderFromParamDesc,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetParamElementNum,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetParamDescSize,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetParamDescFromParamDescArrayByName,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetIndexFromParamDescArrayByName,
  CNPAPI_CNRT_TRACE_CBID_cnrtTransDataOrder,
  CNPAPI_CNRT_TRACE_CBID_cnrtTransOrderAndCast,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetOutputDataSize,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetInputDataSize,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetOutputDataType,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetInputDataType,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetInputDataShape,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetOutputDataShape,
  CNPAPI_CNRT_TRACE_CBID_cnrtCastDataType,
  CNPAPI_CNRT_TRACE_CBID_cnrtCreateQuantizedParam,
  CNPAPI_CNRT_TRACE_CBID_cnrtCreateQuantizedParamByChannel,
  CNPAPI_CNRT_TRACE_CBID_cnrtDestroyQuantizedParam,
  CNPAPI_CNRT_TRACE_CBID_cnrtAddDataStride,
  CNPAPI_CNRT_TRACE_CBID_cnrtWaitNotifier,
  CNPAPI_CNRT_TRACE_CBID_cnrtQueryNotifier,
  CNPAPI_CNRT_TRACE_CBID_cnrtQueueWaitNotifier,
  CNPAPI_CNRT_TRACE_CBID_cnrtQueryModelLocalMemSize,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetModelLevelFromFile,
  CNPAPI_CNRT_TRACE_CBID_cnrtMap,
  CNPAPI_CNRT_TRACE_CBID_cnrtUnmap,
  CNPAPI_CNRT_TRACE_CBID_cnrtFindDevAddrByMappedAddr,
  CNPAPI_CNRT_TRACE_CBID_cnrtCacheOperation,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetLocalMem,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetLocalMem,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetPeerAccessibility,
  CNPAPI_CNRT_TRACE_CBID_cnrtMemcpyPeer,
  CNPAPI_CNRT_TRACE_CBID_cnrtAcquireMemHandle,
  CNPAPI_CNRT_TRACE_CBID_cnrtMapMemHandle,
  CNPAPI_CNRT_TRACE_CBID_cnrtUnMapMemHandle,
  CNPAPI_CNRT_TRACE_CBID_cnrtMemcpyAsync,
  CNPAPI_CNRT_TRACE_CBID_cnrtSetCurrentContextDevice,
  CNPAPI_CNRT_TRACE_CBID_cnrtRuntimeContextMallocBySizeArray,
  CNPAPI_CNRT_TRACE_CBID_cnrtRuntimeContextCreateNotifier,
  CNPAPI_CNRT_TRACE_CBID_cnrtCreateKernelInitParam,
  CNPAPI_CNRT_TRACE_CBID_cnrtDestroyKernelInitParamAndMemory,
  CNPAPI_CNRT_TRACE_CBID_cnrtInitKernelMemory,
  CNPAPI_CNRT_TRACE_CBID_cnrtInvokeKernel_V3,
  CNPAPI_CNRT_TRACE_CBID_cnrtInvokeKernel_V2,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetDeviceInfo,
  CNPAPI_CNRT_TRACE_CBID_cnrtInferFunctionOutputShape,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetParamIndexByName,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetSupportedParamShapeByName,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetSupportedParamDimNumberByName,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetSupportedParamDataTypeByName,
  CNPAPI_CNRT_TRACE_CBID_cnrtGetSupportedParamLayoutByName,
  CNPAPI_CNRT_TRACE_CBID_SIZE
} cnpapi_CallbackIdCNRT;
#ifdef __cplusplus
}
#endif

#endif
